name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (Python)
        run: pip install -r requirements.txt || true
      - name: Install dependencies (Node)
        run: npm ci || true
      - name: Lint
        run: echo "Add linters in each project"
