services:
  api:
    build: .
    container_name: ai-workflow-automator-api
    ports:
      - "8015:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
